version: '3.8'

services:
  backend:
    build: .
    container_name: golang-chatapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - chatnet
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chatnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatapp-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - chatnet
    depends_on:
      - mongo

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: chatapp-websocket
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - chatnet
    depends_on:
      - mongo

networks:
  chatnet:


volumes:
  mongo-data:
